; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PAM-RDP-Heartbeat"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "PAM-Exchange"
#define MyAppURL "https://github.com/PAM-Exchange"
#define MyAppExeName "pam-rdp-heartbeat.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{176FD391-888F-4E2F-BD9D-580924120641}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppPublisher}
LicenseFile=.\dist\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PAM-RDP-Heartbeat-Install-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: ".\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\dist\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\PAM RDP Heartbeat"; Filename: "{app}\{#MyAppExeName}"
;Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Registry]
Root: HKLM; Subkey: "Software\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#MyAppPublisher}"; Flags: uninsdeletekeyifempty

;Registry data from file Heartbeat.reg
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "HeartbeatMinimum"; ValueData: $0000000a; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "RefreshMinimum"; ValueData: $00000005; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "StartMinimized"; ValueData: $00000000; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "ScreenSaverRequired"; ValueData: $00000001; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "ScreenSaverIdleMaximum"; ValueData: $00000384; Flags: uninsdeletevalue

Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listColDurationWdt"; ValueData: $00000037; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listColPIDWdt"; ValueData: $00000032; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listColStartWdt"; ValueData: $00000037; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listColStateWdt"; ValueData: $00000000; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listColTitleWdt"; ValueData: $000000aa; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}"; ValueType: dword; ValueName: "listRows"; ValueData: $0000000a; Flags: uninsdeletevalue

Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "btnCancelTxt"; ValueData: "&Cancel"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "btnCloseTxt"; ValueData: "&Close"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "btnExitTxt"; ValueData: "E&xit"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "btnUpdateTxt"; ValueData: "&Update"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "HeartbeatFrequencyTxt"; ValueData: "&Heartbeat frequency (sec)"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "listColDurationTxt"; ValueData: "Duration"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "listColPIDTxt"; ValueData: "PID"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "listColStartTxt"; ValueData: "Start"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "listColStateTxt"; ValueData: "State"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "listColTitleTxt"; ValueData: "Title"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuActionMinimizeAllTxt"; ValueData: "&Minimize All"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuActionRefreshTxt"; ValueData: "&Refresh"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuActionShowAllTxt"; ValueData: "&Show All"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuActionTxt"; ValueData: "&Action"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuFileExitTxt"; ValueData: "E&xit"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuFileTxt"; ValueData: "&File"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuHelpAboutTxt"; ValueData: "&About"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuHelpQuickGuideTxt"; ValueData: "Quick &guide"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuHelpTxt"; ValueData: "&Help"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuSettingsPreferencesTxt"; ValueData: "&Preferences"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuSettingsStartMinimizedTxt"; ValueData: "Start &Minimized"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuSettingsStayOnTopTxt"; ValueData: "Stay on &Top"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "mnuSettingsTxt"; ValueData: "&Settings"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "RefreshFrequencyTxt"; ValueData: "&Refresh frequency (sec)"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "StartMinimizedTxt"; ValueData: "Start &Minimized"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "StayOnTopTxt"; ValueData: "Stay on &Top"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "QuickGuideTxt"; ValueData: "In the menu item 'Settings > Preferences' timers for background actions can be defined. The heartbeat timer will control how often the heartbeat is send to both active and hidden RDP sessions. The value should depend of the timeout values defined on the servers connected to from the Desktop. Typically, sending a heartbeat signal every 30'th second is sufficient. The refresh timer will control how often the list of RDP sessions is updated. Typical values are every 10 to 30 seconds. It is also possible to refress the list manually by pressiong F5. The flags 'Stay on Top' and 'Start Minimized' are controlling the PAM RDP Heartbeat window behaviour.\n\nAlt-Ctrl-ScrollLock\nWill show/activate or hide the GUI window. This will work even when showing an RDP fullscreen session.\n\nWhen the PAM RDP Heartbeat GUI is active, additional functions are available.\n\nAlt-Ctrl-Down\nMinimize/hide all RDP windows.\n\nAlt-Ctrl-Up\nRestore all hidden RDP windows.\n\nF5\nManually refresh the list of RDP sessions."; Flags: uninsdeletevalue
Root: HKLM; Subkey: "SOFTWARE\{#MyAppPublisher}\{#MyAppName}\en-US"; ValueType: string; ValueName: "AboutTxt"; ValueData: "The program sends heartbeat signals to RDP sessions. When RDP sessions are minimized, the RDP GUI is hidden and heartbeat messages are still being accepted by the session."; Flags: uninsdeletevalue
;End of registry data from file Heartbeat.reg
;SOME KEYS FILTERED DUE TO PRIVILEGESREQUIRED SETTINGS!
